### ISSUE TITLE
[QUESTION]DataGrip 无法正常获取各表格字段信息

### ISSUE THREAD

**Issue by JokerRun** [aliyun/aliyun-odps-jdbc#129]
按照MaxCompute官方文档，使用通过DataGrip使用ODPS JDBC驱动建立连接后，无法正常获取表格字段信息：

![image](https://user-images.githubusercontent.com/31248028/138021970-24c69b9e-ff20-48f9-87f0-76c108da33d2.png)

DataGrip日志：
![image](https://user-images.githubusercontent.com/31248028/138022064-561180e3-729b-4241-820a-b893f8e0fb2c.png)

```
2021-10-20 03:15:29,545 [ 892261]   WARN - lij.database.util.ErrorHandler -  
java.sql.SQLException
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getSearchStringEscape(OdpsDatabaseMetaData.java:270)
	at com.intellij.database.remote.jdbc.impl.RemoteDatabaseMetaDataImpl.getSearchStringEscape(RemoteDatabaseMetaDataImpl.java:689)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
```

**Comment by JokerRun** [comment]
https://help.aliyun.com/document_detail/281088.html

另外，官网的文档里面连接成功后的截图，看上去可能也是有这个黄色警告⚠️，是不是这个演示文档本身操作的时候就有遇到这个问题了(以下是帮助文档中的截图，右下角也有黄色警告的event log)？

![image](https://user-images.githubusercontent.com/31248028/138022591-d06591dc-1498-41e0-be72-772aada3feff.png)
