### ISSUE TITLE
SELECT null FROM project.table 不能执行？

### ISSUE THREAD

**Issue by BillLucky** [aliyun/aliyun-odps-jdbc#31]
问题背景：
   发现使用JDBC跑 SELECT null FROM project.table 时，一直报错500. 
   但是使用ODPS Web页面 和 SQLTask.run(odps,sql) 可以执行并且拿到结果。

问题重现：
  使用JDBC查询任意一张表，语法如下：
  SELECT null from project.table  // 注意 查询列处写null就好，这个按理说应该是支持的写法。

就能看到错误了。 

我这边错误如下：

> `-----------------------------testRunSQLTask------------------------------------ 
java.sql.SQLException: RequestId=xxxxxxxxx, ErrorCode=InternalServerError, ErrorMessage=Service internal error, please try again later.
-----------------------------testRunSQLTask------------------------------------	at com.aliyun.odps.jdbc.OdpsForwardResultSet.rebuildReader(OdpsForwardResultSet.java:177)
	at com.aliyun.odps.jdbc.OdpsForwardResultSet.next(OdpsForwardResultSet.java:131)
	at com.wuage.dp.ODPSOfficialDemoOfJDBCTest.printResultSetData(ODPSOfficialDemoOfJDBCTest.java:118)
	at com.wuage.dp.ODPSOfficialDemoOfJDBCTest.testRunSQLTask(ODPSOfficialDemoOfJDBCTest.java:151)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: RequestId=20170327112505af389a0a008ecef5, ErrorCode=InternalServerError, ErrorMessage=Service internal error, please try again later.
	at com.aliyun.odps.tunnel.io.RawTunnelRecordReader.createInstanceTunnelReader(RawTunnelRecordReader.java:96)
	at com.aliyun.odps.tunnel.io.TunnelRecordReader.createNewReader(TunnelRecordReader.java:238)
	at com.aliyun.odps.tunnel.io.TunnelRecordReader.<init>(TunnelRecordReader.java:169)
	at com.aliyun.odps.tunnel.InstanceTunnel$DownloadSession.openRecordReader(InstanceTunnel.java:289)
	at com.aliyun.odps.tunnel.InstanceTunnel$DownloadSession.openRecordReader(InstanceTunnel.java:270)
	at com.aliyun.odps.tunnel.InstanceTunnel$DownloadSession.openRecordReader(InstanceTunnel.java:232)
	at com.aliyun.odps.jdbc.OdpsForwardResultSet.rebuildReader(OdpsForwardResultSet.java:172)
	... 28 more
`

**Comment by emerson-zhao** [comment]
这种写法在odps jdbc中没有太大意义，所以之前odps jdbc并不承诺可以运行，但是当你的project打开odps2.0的相关开关后，该sql在odps jdbc中也是可以运行的。我们后续会考虑在odps1.0的模式下也做兼容。

**Comment by BillLucky** [comment]
好的，感谢。
之所以出现这种写法，是我这边在使用Presto用JDBC接入ODPS时发现Presto会把count语句转换成这种，现在我把它改成：SELECT 1 FROM project.table ；了，也能实现效果。
