### ISSUE TITLE
odps-jdbc能配合Mybatis来查询odps吗？

### ISSUE THREAD

**Issue by eejwtang** [aliyun/aliyun-odps-jdbc#40]
我使用文档中JDBC的连接方法，成功连接我的ODPS项目并且可以查询操作数据，因为我的工程用的是Mybatics框架，所以我希望能用Mybatics配合odps-jdbc来查询数据库。我配好Mybatics连接环境（driver、url、accessid、accesskey）之后，测试Mybatics连接ODPS，总是会报error和这个异常SQLFeatureNotSupportedException。google一番没找到解决方法，希望这里能得到帮助，谢谢。
```
Exception in thread "main" org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported
### Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:58)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy3.test(Unknown Source)
	at test.MyBaticsConnectOdpsTest.main(MyBaticsConnectOdpsTest.java:29)
Caused by: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.setDesiredAutoCommit(JdbcTransaction.java:108)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:143)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:338)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:49)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 5 more
Caused by: java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported
	at com.aliyun.odps.jdbc.OdpsConnection.setAutoCommit(OdpsConnection.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.datasource.pooled.PooledConnection.invoke(PooledConnection.java:245)
	at com.sun.proxy.$Proxy5.setAutoCommit(Unknown Source)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.setDesiredAutoCommit(JdbcTransaction.java:103)
	... 13 more
```

**Comment by lyman** [comment]
报这个错是因为 mybatis 在尝试对 odps jdbc 的 connection 执行 setAutoCommit(false)

看代码

```
  @Override
  public void setAutoCommit(boolean autoCommit) throws SQLException {
    if (!autoCommit) {
      log.error(Thread.currentThread().getStackTrace()[1].getMethodName()
          + " to false is not supported!!!");
      throw new SQLFeatureNotSupportedException("enabling autocommit is not supported");
    }
  }

  @Override
  public boolean getAutoCommit() throws SQLException {
    return true;
  `}`
```

MaxCompute 的 SQL 执行全都是 auto commit 的，driver 不允许将其设置为 false。不是很清楚 mybatis 是否有配置可以不要执行 setAutoCommit(false)

**Comment by eejwtang** [comment]
改变Mybatics的初始化，把setAutoCommit设置为true就可以了，谢谢。
