### ISSUE TITLE
java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported

### ISSUE THREAD

**Issue by Malaban** [aliyun/aliyun-odps-jdbc#58]
Mybatis集成odps，配置多数据源，项目报错无法启动。
druid-spring-boot-starter', version: '1.1.9'
odps-sdk-core', version: '0.28.4-public'
'odps-jdbc', version: '1.7'
**错误信息如下**：
571640d1a6dd [INFO] ODPS JDBC driver, Version 1.7
571640d1a6dd [INFO] endpoint=***, project=***
571640d1a6dd [SEVERE] setAutoCommit is not supported!!!
571640d1a6dd [INFO] connection closed
2019-10-10 09:27:42.360 ERROR Druid-ConnectionPool-Create-859162259 com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread 2469 run --create connection SQLException, url: jdbc:odps:http://10.8.102.192/api?project=lab_ghq&amp;characterEncoding=UTF-8, errorCode 0, state null java.sql.SQLFeatureNotSupportedException: enabling autocommit is not supported
	at com.aliyun.odps.jdbc.OdpsConnection.setAutoCommit(OdpsConnection.java:237) ~[odps-jdbc-1.7.jar:?]
	at com.alibaba.druid.pool.DruidAbstractDataSource.initPhysicalConnection(DruidAbstractDataSource.java:1649) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1585) ~[druid-1.1.9.jar:1.1.9]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2466) [druid-1.1.9.jar:1.1.9]

**Comment by lyman** [comment]
MaxCompute 没有 commit 概念，找下 druid 的配置把 autocommit 关掉。参考 https://github.com/alibaba/druid/issues/2235

**Comment by Malaban** [comment]
已经关了，这是我们配置文件。我们是打算做多数据源，一个mysql，一个odps。配置了那个选项还是不行。
spring.shardingsphere.datasource.names = ds,ds1
spring.shardingsphere.datasource.ds.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds.driver-class-name = com.mysql.cj.jdbc.Driver
spring.shardingsphere.datasource.ds.url = ***
spring.shardingsphere.datasource.ds.username = ***
spring.shardingsphere.datasource.ds.password = ***
spring.shardingsphere.datasource.ds.max-total = 100




spring.shardingsphere.datasource.ds1.type = com.alibaba.druid.pool.DruidDataSource
spring.shardingsphere.datasource.ds1.url = jdbc:odps:http://***/**?project=***&amp;characterEncoding=UTF-8
spring.shardingsphere.datasource.ds1.username = ***
spring.shardingsphere.datasource.ds1.password = ***
spring.shardingsphere.datasource.ds1.defaultAutoCommit = true

**Comment by lyman** [comment]
autocommit 要为 true

https://github.com/aliyun/aliyun-odps-jdbc/blob/master/src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java#L238

**Comment by Malaban** [comment]
好的.我再试试


| |
uuid0717
|
|
邮箱：uuid0717@163.com
|

Signature is customized by Netease Mail Master

On 10/10/2019 10:39, Li Ruibo wrote:

autocommit 要为 true

https://github.com/aliyun/aliyun-odps-jdbc/blob/master/src/main/java/com/aliyun/odps/jdbc/OdpsConnection.java#L238
