### ISSUE TITLE
cann't use jdbc to get metadata

### ISSUE THREAD

**Issue by davidaman** [aliyun/aliyun-odps-jdbc#99]
2020-10-26 15:00:27.164 ERROR 17526 --- [lerBak_Worker-1] com.aliyun.odps.jdbc.OdpsConnection      : getTables fails:

com.aliyun.odps.NoSuchObjectException: ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	at com.aliyun.odps.rest.RestClient.handleErrorResponse(RestClient.java:376) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:321) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:277) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:229) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.stringRequest(RestClient.java:206) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTablesInternal(Tables.java:737) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTables(Tables.java:657) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTables(Tables.java:630) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.convertTablesToRows(OdpsDatabaseMetaData.java:799) ~[odps-jdbc-3.0.1.jar!/:na]
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:769) ~[odps-jdbc-3.0.1.jar!/:na]
	at com.cubigdata.dam.metadata.etl.jdbc.operator.JdbcMetaOperator.list(JdbcMetaOperator.java:48) [metadata-etl-0.6.0.jar!/:na]
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils$3.processRow(EtlMetaUtils.java:107) [metadata-etl-0.6.0.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1607) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils.syncDatasource(EtlMetaUtils.java:103) [metadata-etl-0.6.0.jar!/:na]
	at com.cubigdata.dam.metadata.schedule.jobs.MetadataIngestionJob.execute(MetadataIngestionJob.java:42) [classes!/:0.0.1-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:na]
Caused by: com.aliyun.odps.rest.RestException: RequestId=5F96740AC03EDBB601B635B8,Code=NoSuchObject,Message=ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	... 22 common frames omitted

2020-10-26 15:00:27.164 ERROR 17526 --- [lerBak_Worker-1] com.aliyun.odps.jdbc.PublicMethodAspect  : exception happened:
2020-10-26 15:00:27.165 ERROR 17526 --- [lerBak_Worker-1] com.aliyun.odps.jdbc.PublicMethodAspect  : java.sql.SQLException: getTables fails:
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:777)
	at com.cubigdata.dam.metadata.etl.jdbc.operator.JdbcMetaOperator.list(JdbcMetaOperator.java:48)
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils$3.processRow(EtlMetaUtils.java:107)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1607)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils.syncDatasource(EtlMetaUtils.java:103)
	at com.cubigdata.dam.metadata.schedule.jobs.MetadataIngestionJob.execute(MetadataIngestionJob.java:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: [404] com.aliyun.odps.NoSuchObjectException: ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	at com.aliyun.odps.rest.RestClient.handleErrorResponse(RestClient.java:376)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:321)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:277)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:229)
	at com.aliyun.odps.rest.RestClient.stringRequest(RestClient.java:206)
	at com.aliyun.odps.Tables.loadTablesInternal(Tables.java:737)
	at com.aliyun.odps.Tables.loadTables(Tables.java:657)
	at com.aliyun.odps.Tables.loadTables(Tables.java:630)
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.convertTablesToRows(OdpsDatabaseMetaData.java:799)
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:769)
	... 12 more
Caused by: com.aliyun.odps.rest.RestException: RequestId=5F96740AC03EDBB601B635B8,Code=NoSuchObject,Message=ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	... 22 more

2020-10-26 15:00:27.165 ERROR 17526 --- [lerBak_Worker-1] com.aliyun.odps.jdbc.PublicMethodAspect  : exception happened:

java.sql.SQLException: getTables fails:
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:777) ~[odps-jdbc-3.0.1.jar!/:na]
	at com.cubigdata.dam.metadata.etl.jdbc.operator.JdbcMetaOperator.list(JdbcMetaOperator.java:48) [metadata-etl-0.6.0.jar!/:na]
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils$3.processRow(EtlMetaUtils.java:107) [metadata-etl-0.6.0.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1607) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723) [spring-jdbc-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils.syncDatasource(EtlMetaUtils.java:103) [metadata-etl-0.6.0.jar!/:na]
	at com.cubigdata.dam.metadata.schedule.jobs.MetadataIngestionJob.execute(MetadataIngestionJob.java:42) [classes!/:0.0.1-SNAPSHOT]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [quartz-2.3.2.jar!/:na]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) [quartz-2.3.2.jar!/:na]
Caused by: com.aliyun.odps.NoSuchObjectException: ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	at com.aliyun.odps.rest.RestClient.handleErrorResponse(RestClient.java:376) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:321) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:277) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:229) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.rest.RestClient.stringRequest(RestClient.java:206) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTablesInternal(Tables.java:737) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTables(Tables.java:657) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.Tables.loadTables(Tables.java:630) ~[odps-sdk-core-0.32.5-public-shaded.jar!/:0.32.5-public]
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.convertTablesToRows(OdpsDatabaseMetaData.java:799) ~[odps-jdbc-3.0.1.jar!/:na]
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:769) ~[odps-jdbc-3.0.1.jar!/:na]
	... 12 common frames omitted
Caused by: com.aliyun.odps.rest.RestException: RequestId=5F96740AC03EDBB601B635B8,Code=NoSuchObject,Message=ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	... 22 common frames omitted

java.sql.SQLException: getTables fails:
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:777)
	at com.cubigdata.dam.metadata.etl.jdbc.operator.JdbcMetaOperator.list(JdbcMetaOperator.java:48)
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils$3.processRow(EtlMetaUtils.java:107)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1607)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:694)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
	at com.cubigdata.dam.metadata.etl.utils.EtlMetaUtils.syncDatasource(EtlMetaUtils.java:103)
	at com.cubigdata.dam.metadata.schedule.jobs.MetadataIngestionJob.execute(MetadataIngestionJob.java:42)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: [404] com.aliyun.odps.NoSuchObjectException: ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	at com.aliyun.odps.rest.RestClient.handleErrorResponse(RestClient.java:376)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:321)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:277)
	at com.aliyun.odps.rest.RestClient.request(RestClient.java:229)
	at com.aliyun.odps.rest.RestClient.stringRequest(RestClient.java:206)
	at com.aliyun.odps.Tables.loadTablesInternal(Tables.java:737)
	at com.aliyun.odps.Tables.loadTables(Tables.java:657)
	at com.aliyun.odps.Tables.loadTables(Tables.java:630)
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.convertTablesToRows(OdpsDatabaseMetaData.java:799)
	at com.aliyun.odps.jdbc.OdpsDatabaseMetaData.getTables(OdpsDatabaseMetaData.java:769)
	... 12 more
Caused by: com.aliyun.odps.rest.RestException: RequestId=5F96740AC03EDBB601B635B8,Code=NoSuchObject,Message=ODPS-0130131:Table not found - 'rkk_test.p_std_qz_biz_0800_cgzfwf_snapshot_16036955600220' table not found
	... 22 more
2020-10-26 15:00:27.166 ERROR 17526 --- [lerBak_Worker-1] c.c.d.m.e.j.operator.JdbcMetaOperator    : 报错了：java.sql.SQLException: getTables fails:

my pom file is here:
<dependency>
			<groupId>com.aliyun.odps</groupId>
			<artifactId>odps-jdbc</artifactId>
			<version>3.0.1</version>
		</dependency>

**Comment by davidaman** [comment]
I want to ignore not exist tables and continue to get exist ones, how can I do?

**Comment by cornmonster** [comment]
> I want to ignore not exist tables and continue to get exist ones, how can I do?

Could you update the JDBC Driver to latest version and try it again?
